[workspace]
resolver = "2"

members = [
    "exalt-ast",
    "exalt-assembler",
    "exalt-cli",
    "exalt-compiler",
    "exalt-decompiler",
    "exalt-disassembler",
    "exalt-lir",
    "exalt-testing",
    "exalt-completions",
]
