[workspace]

members = [
    "exalt-ast",
    "exalt-assembler",
    "exalt-build",
	"exalt-cli",
    "exalt-compiler",
    "exalt-decompiler",
    "exalt-disassembler",
	"exalt-lir",
    "exalt-testing"
]