[package]
name = "exalt-disassembler"
version = "0.1.0"
edition = "2021"

[dependencies]
exalt-lir = { path = "../exalt-lir" }
anyhow = "1.0.57"
byteorder = "1.4.3"
encoding_rs = "0.8.31"
lazy_static = "1.4.0"
maplit = "1.0.2"
rustc-hash = "1.1.0"
