[package]
name = "exalt-build"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
exalt-lir = { path = "../exalt-lir" }
toml = "0.5.9"
anyhow = "1.0.57"
